image: node:22.14.0

definitions:
  steps:
    - step: &yarninstall_and_codegen
        name: Yarn install and codegen
        caches:
          - node
        script:
          - yarn install --frozen-lockfile
          - yarn run build
          - yarn run graphql-codegen

pipelines:
  default:
    - step: *yarninstall_and_codegen
    - step:
        name: Build and check types
        caches:
          - node
        script:
          - yarn run build
    - step:
        name: Lint
        caches:
          - node
        script:
          - yarn run lint
    - step:
        name: Test
        caches:
          - node
        script:
          - yarn run test
    - step:
        name: Bundle module tgz
        caches:
          - node
        script:
          - apt update && apt install -y jq
          - yarn run build:module
        artifacts:
          - 'companion-module-audinate-dante-ddm.tgz'
